version: '3'

services:
  db:
    image: mariadb:11.1
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=hedgedoc
    volumes:
      - database:/var/lib/mysql
        # - ./resources/utf8.cnf:/etc/mysql/conf.d/utf8.cnf
    networks:
      backend:

  app:
    image: quay.io/hedgedoc/hedgedoc:1.9.9-debian
    restart: always
    environment:
      - MYSQL_DATABASE=hedgedoc
        # - CMD_PROTOCOL_USESSL=true
        # - CMD_HSTS_ENABLE=true
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_ALLOW_EMAIL_REGISTER=false
    volumes:
      - uploads:/hedgedoc/public/uploads
    networks:
      backend:
      frontend:
    depends_on:
      - db

networks:
  backend:
    internal: true
  frontend:

volumes:
  database:
  uploads:
